backend:
  name: git-gateway

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/blog/architure-engineering" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "author", name: "author", widget: "string"}
      - {label: "type", name: "type", widget: "string", required: false}
      - {label: "url", name: "url", widget: "string", required: false}
      - {label: "categories", name: "categories", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"} 
  - name: "pages"
    label: "media-coverage"
    files:
      - file: "content/media-coverage/_index.md"
        label: "media coverage Page"
        name: "media-coverage"
        fields:
          - {label: Title, name: title, widget: string}
          
      